name: beckmann
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rdkit>=2022.03.1
  - numpy
  - pandas
  - matplotlib
  - pillow
  - pip
  - pip:
    - auto3d
    - torch
    - tqdm
    - psutil
    - pyyaml
    - "aimnet[ase]"